### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by angelpl16** [angelpl16/GESPRO_GESTIONTAREAS#21]
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb

**Comment by VictorVaqueroUBU** [comment]
![image](https://user-images.githubusercontent.com/118168256/203125849-8bf13481-525f-4b76-bb0f-9b104db5c5ab.png)[
](https://medium.com/@ferrand.d/can-you-and-should-you-use-vector-drawables-a-cheatsheet-32a2e1cc2ecf#.eoek6mlry)

**Comment by VictorVaqueroUBU** [comment]
https://medium.com/@ferrand.d/can-you-and-should-you-use-vector-drawables-a-cheatsheet-32a2e1cc2ecf#.eoek6mlry
