### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by angelpl16** [angelpl16/GESPRO_GESTIONTAREAS#25]
https://support.google.com/googleplay/android-developer/answer/113469#privacy

https://www.raywenderlich.com/122114/android-app-distribution-tutorial-zero-google-play-store

**Comment by VictorVaqueroUBU** [comment]
![image](https://user-images.githubusercontent.com/118168256/203127680-f5b1bd2a-5d9c-496c-9c63-d1a841567fcc.png)
![image](https://user-images.githubusercontent.com/118168256/203127711-2764e3bf-4f24-4587-95a5-e0e43ed2ea09.png)
![image](https://user-images.githubusercontent.com/118168256/203127745-f73c44ab-0e86-4ba0-91d4-d03a2214b0dd.png)
![image](https://user-images.githubusercontent.com/118168256/203127765-39bbe1d1-db83-4f49-a969-2813418eac96.png)
![image](https://user-images.githubusercontent.com/118168256/203127788-335a7da8-d662-4e1e-a028-aeb6a438d59a.png)
![image](https://user-images.githubusercontent.com/118168256/203127826-ba8164d4-e805-4b0c-b016-a37290d96a43.png)

**Comment by VictorVaqueroUBU** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees
